# CircleCI Configuration File

version: 2.1

orbs:
  node: circleci/node@7.2.1

jobs:
  build-app:
     docker:
        - image: cimg/node:26.1.0
     resource_class: small
     steps:
        - checkout
        - node/install-packages
        - run:
             name: Build The Application
             command: npm run build
  deploy-app:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run:
           name: Call Deploy Webhook
           command: echo "A webhook to be called"

workflows:
  build_and_deploy:
    jobs:
      - build-app
      - deploy-app:
          requires:
            - build-app
